version: '3.3'
services:
  database:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
      - MYSQL_USER=dxpcloud
      - MYSQL_PASSWORD=dxpcloud
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
  liferay:
    build:
      context: ./liferay/build/docker
    environment:
      - LIFERAY_JAVA_OPTS=-Xms2g -Xmx2g
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
    ports:
      - "127.0.0.1:11311:11311"
    volumes:
      - type: volume
        source: liferay-data
        target: /opt/liferay/data
    depends_on:
      - database
      - search
  search:
    image: "liferaycloud/elasticsearch:6.8.6-4.0.0"
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_SERVICE_SCALE=1
      - LCP_SERVICE_ID=search
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
  webserver:
    image: "liferaycloud/nginx:1.16.1-4.0.0"
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - liferay
volumes:
  liferay-data:
  database-data:
